/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'stm32g030_smart_sevensegment_driver' 
 * Target:  'STM32G030F6P6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g0xx.h"

/* Keil::Device:Startup@1.4.2 */
#define RTE_DEVICE_STARTUP_STM32G0XX    /* Device Startup for STM32G0 */


#endif /* RTE_COMPONENTS_H */
